version: '3'
x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
services:
  tor:
    container_name: fail-tor
    build:
      context: .
      dockerfile: Dockerfile-tor
    restart: unless-stopped
    ports:
      - 127.0.0.1:9050:9050
    <<: *log-config
  i2p:
    container_name: fail-i2p
    build:
      context: .
      dockerfile: Dockerfile-i2p
    restart: unless-stopped
    ports:
        - 127.0.0.1:4444:4444
    <<: *log-config
